### PR TITLE
Show resource names instead of IDs

### PR DESCRIPTION
**Pull request by s12v**
*Issue #:* #29 (partially)

*Description of changes:*
Use resource name if available, fall back to ID.

Note: there's no tests, I'm not entirely sure if it works as expected, please check.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ConnorKirk** [comment]
Hi @s12v 
Thanks for this PR!
This is a feature we would like to add. 

We intend to test this feature. We will come back to you with what we find.

**Comment by svozza** [comment]
So I've looked into this a bit more and unfortunately this won't probably have the effect required, the reason why is that `resourceName` and `resourceId` come from AWS Config and for the items we're interested in like VPCs, subnets etc, Config only gives us the `resourceId`. However, for the other items like Lambda, that actually have a `resourceName`, it's normally the same as `resourceId` so it doesn't matter which we use. I'm still inclined to merge your pull request because I don't think it will do any harm but I don't think it will make an appreciable difference in the way we display items on the front end. This will require more thought on our side.

**Comment by s12v** [comment]
@svozza, it's intended to cover some resources, that have `resourceName` and it's more descriptive than ID. I had in mind RDS instances and SQS queues.

Right now, looking at DB instances, it's a long list of items like
```
db-ODVUQ7RJMOX4C3............
db-XXXXXXXXXXXXXX............
db-XXXXXXXXXXXXXX............
```

For example looking at the Neptune instance used by Perspective, it has these properties in the Config JSON:
```
"resourceId": "db-ODVUQ7RJMOX4C3............",
"resourceName": "neptunedbinstance-gebrq......",
```

While `neptunedbinstance-gebrq......` is not the most descriptive name, I think it's much better then the ID.

**Comment by svozza** [comment]
Yep, it's definitely an improvement. I would prefer an implementation that relies on a null check rather than using the `in` keyward (no need to worry about prototype chains etc. Would you be willing to update the PR to look something like this?

```js
const buildGeneric = ({properties}) => {
    properties.title = R.defaultTo(properties.resourceId, properties.resourceName);
}
```

Alternatively I can take over the PR (there's a few other changes in the file I'd like to make).

**Comment by s12v** [comment]
@svozza, updated the PR. Thanks. You can of course take over the PR if you'd like.

**Comment by svozza** [comment]
Let's merge this actually and I can make changes in a separate PR. Thank you!

**Pull request merged**
